version: '3'

tasks:
  #### Default ####
  default:
    desc: List all tasks
    cmds:
      - task -l
    silent: true

  #### Setup ####
  setup:
    desc: Run all setup tasks
    cmds:
      - task setup:build
      - task setup:dev
    silent: true

  setup:upgrade:
    desc: Upgrade pip
    deps: ['setup:venv']
    cmds:
      - |
        if [ "{{OS}}" == "windows" ]; then
          python -m pip install --upgrade pip
        else
          python3 -m pip install --upgrade pip
        fi
    silent: true

  setup:venv:
    desc: Create and activate virtual environment if it doesn't exist
    cmds:
      # Check if venv exists first
      - |
        if [ "{{OS}}" == "windows" ]; then
          if [ ! -d ".venv" ] || [ ! -f ".venv\Scripts\python.exe" ]; then
            echo "Creating virtual environment..."
            python -m venv .venv
          else
            echo "Virtual environment already exists."
          fi
        else
          if [ ! -d ".venv" ] || [ ! -f ".venv/bin/python" ]; then
            echo "Creating virtual environment..."
            python3 -m venv .venv
          else
            echo "Virtual environment already exists."
          fi
        fi
      # Activation is handled differently per OS
      - |
        if [ "{{OS}}" == "windows" ]; then
          echo "Run: .venv\\Scripts\\activate"
        else
          echo "Run: source .venv/bin/activate"
        fi
    silent: true

  setup:dev:
    desc: Install development dependencies
    deps: ['setup:upgrade']
    cmd: pip install -e ".[dev]"
    silent: true

  setup:build:
    desc: Install build dependencies
    deps: ['setup:upgrade']
    cmd: pip install build hatch
    silent: true

  setup:badge:
    desc: Install genbadge
    deps: ['setup:upgrade']
    cmd: pip install "genbadge[coverage]"
    silent: true

  #### Lint ####
  lint:
    desc: Run all linting tasks
    cmds:
      - task lint:ruff
    silent: true

  lint:ruff:
    desc: Run ruff linter
    cmd: ruff check src tests -q
    silent: true

  #### Format ####
  format:
    desc: Format code
    cmd: ruff format src tests -q
    silent: true

  #### Test ####
  test:
    desc: Run all tests
    cmd: pytest tests/ --disable-warnings --no-cov
    silent: true

  test:junit:
    desc: Run all tests and generate JUnit report
    cmds:
      - pytest tests/ --junitxml=junit.xml --disable-warnings --no-cov
      - echo "JUnit report generated in junit.xml"
    silent: true

  test:core:
    desc: Run core subpackage tests
    cmd: pytest tests/core --no-cov
    silent: true

  test:core:client:
    desc: Run client module tests
    cmd: pytest tests/core/test_client.py --no-cov
    silent: true

  test:core:models:
    desc: Run models module tests
    cmd: pytest tests/core/test_models.py --no-cov
    silent: true

  test:core:adoption:
    desc: Run adoption module tests
    cmd: pytest tests/core/test_adoption.py --no-cov
    silent: true

  test:utils:
    desc: Run utils subpackage tests
    cmd: pytest tests/utils --no-cov
    silent: true

  test:utils:scanner:
    desc: Run scanner module tests
    cmd: pytest tests/utils/test_scanner.py --no-cov
    silent: true

  test:cli:
    desc: Run cli subpackage tests
    cmd: pytest tests/cli --no-cov
    silent: true

  test:cli:commands:
    desc: Run commands module tests
    cmd: pytest tests/cli/test_commands.py --no-cov
    silent: true

  test:cli:printer:
    desc: Run printer module tests
    cmd: pytest tests/cli/test_printer.py --no-cov
    silent: true

  #### Coverage ####
  coverage:
    desc: Generate coverage for all subpackages
    cmds:
      - pytest --cov=ado_template_tracker --disable-warnings tests
      - rm .coverage
    silent: true

  coverage:xml:
    desc: Generate XML coverage report
    deps: ['setup:badge']
    cmds:
      - pytest --cov=src/ado_template_tracker --cov-report=xml
      - echo "Coverage report generated in coverage.xml"
    silent: true

  coverage:report:
    desc: Generate HTML coverage report
    cmds:
      - pytest --cov=src/ado_template_tracker --cov-report=html
      - echo "Coverage report generated in htmlcov/index.html"
    silent: true

  coverage:badge:
    desc: Generate coverage badge
    deps: ['setup:badge']
    cmds:
      - pytest --cov=src/ado_template_tracker --cov-report=xml
      - genbadge coverage -i coverage.xml -o .github/badges/coverage.svg
      - echo "Coverage badge generated in .github/badges/coverage.svg"
    silent: true

  coverage:threshold:
    desc: Check coverage thresholds
    cmds:
      - pytest -q --cov=ado_template_tracker.core --cov-fail-under=85 tests/core
      - pytest -q --cov=ado_template_tracker.utils --cov-fail-under=90 tests/utils
      - pytest -q --cov=ado_template_tracker.cli --cov-fail-under=40 tests/cli
      - rm .coverage
    silent: true

  coverage:core:
    desc: Generate coverage for core subpackage
    cmd: pytest --cov=ado_template_tracker.core tests/core
    silent: true

  coverage:utils:
    desc: Generate coverage for utils subpackage
    cmd: pytest --cov=ado_template_tracker.utils tests/utils
    silent: true

  coverage:cli:
    desc: Generate coverage for cli subpackage
    cmd: pytest --cov=ado_template_tracker.cli tests/cli
    silent: true

  #### Build & Publish ####
  build:
    desc: Build package using hatch
    cmd: hatch build
    silent: true

  publish:test:
    desc: Publish to TestPyPI
    cmd: hatch publish -r test
    silent: true

  publish:release:
    desc: Publish to PyPI
    cmd: hatch publish
    silent: true

  #### Release ####
  version:bump:
    desc: Bump version (patch by default)
    cmds:
      - task: version:{{.CLI_ARGS | default "patch"}}
    silent: true

  version:patch:
    desc: Bump patch version
    cmd: hatch version patch
    silent: true

  version:minor:
    desc: Bump minor version
    cmd: hatch version minor
    silent: true

  version:major:
    desc: Bump major version
    cmd: hatch version major
    silent: true

  #### Clean ####
  clean:
    desc: Clean build artifacts and cache
    cmds:
      - rm -rf build/
      - rm -rf dist/
      - rm -rf .pytest_cache/
      - rm -rf .coverage
      - rm -rf htmlcov/
      - rm -rf .mypy_cache/
      - rm -rf .ruff_cache/
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
    silent: true
    ignore_error: true

  clean:all:
    desc: Clean all, including virtual environment
    cmds:
      - task: clean
      - rm -rf .venv/
    silent: true
    ignore_error: true

  #### CLI ####
  cli:
    desc: Run the CLI tool
    cmd: python -m ado_template_tracker {{.CLI_ARGS}}
    silent: true

  #### Init __init__.py ####
  init:version:
    desc: Initialize or update version in __init__.py
    cmds:
      - |
        if [ ! -f src/ado_template_tracker/__init__.py ] || ! grep -q "__version__" src/ado_template_tracker/__init__.py; then
          echo '__version__ = "0.1.0"' > src/ado_template_tracker/__init__.py
          echo "Version initialized to 0.1.0 in __init__.py"
        else
          echo "Version already exists in __init__.py"
        fi
    silent: true
